version: '3.4'

services:

  bis-api-prod:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "30010:80"
    build:
      context: ./src/BisApi
      dockerfile: Dockerfile

  bis-api-staging:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "30020:80"
    build:
      context: ./src/BisApi
      dockerfile: Dockerfile

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.53.0
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55679:55679" # zpages extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"
